//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS470_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Author
    {
        public int AuthorId { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public int NumBooksWritten { get; set; }
    }
}
