//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS470_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int ISBN { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public int Year { get; set; }
        public int Rating { get; set; }
        public int NumPages { get; set; }
        public int PublisherID { get; set; }
        public int GenreID { get; set; }
    }
}
