//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS470_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestGamesTable
    {
        public int Id { get; set; }
        public Nullable<int> GameID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Rating { get; set; }
        public Nullable<int> GenreID { get; set; }
        public Nullable<int> PublisherID { get; set; }
        public Nullable<int> ProducerID { get; set; }
    }
}
